// samples/02-frontend/test-03-vue-vite/src/App.vue
<template>
  <div class="container">
    <h1>{{ title }}</h1>
    <p class="description">{{ description }}</p>
    
    <div class="counter-section">
      <p class="count">{{ count }}</p>
      <button @click="increment" class="btn">
        Click Me
      </button>
    </div>
    
    <div class="tech-stack">
      <p class="tech-title">技术栈：</p>
      <p class="tech-list">Vue 3 + Vite</p>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'

const title = ref('Vue + Vite Test')
const description = ref('DemoGo 构建产物测试')
const count = ref(0)

const increment = () => {
  count.value++
}
</script>

<style scoped>
.container {
  background: white;
  padding: 2rem;
  border-radius: 12px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
  text-align: center;
  max-width: 400px;
  width: 90%;
}

h1 {
  color: #333;
  margin-bottom: 1rem;
  font-size: 1.8rem;
}

.description {
  color: #666;
  margin-bottom: 2rem;
  font-size: 1.1rem;
}

.counter-section {
  margin-bottom: 2rem;
}

.count {
  font-size: 3rem;
  font-weight: bold;
  color: #42b883;
  margin-bottom: 1rem;
}

.btn {
  padding: 0.75rem 1.5rem;
  font-size: 1rem;
  background-color: #42b883;
  color: white;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  transition: background-color 0.2s;
}

.btn:hover {
  background-color: #36a072;
}

.tech-stack {
  padding: 1rem;
  background-color: #f8f9fa;
  border-radius: 8px;
}

.tech-title {
  font-weight: bold;
  margin-bottom: 0.5rem;
  color: #333;
}

.tech-list {
  color: #666;
}
</style>

// samples/02-frontend/svelte-vite/src/App.svelte
<script>
  let count = 0;

  function increment() {
    count += 1;
  }
</script>

<main>
  <h1>🎉 Hello Svelte!</h1>
  <p class="subtitle">Svelte + Vite 项目示例</p>
  
  <div class="counter">
    <p>计数: {count}</p>
    <button on:click={increment}>
      点击 +1
    </button>
  </div>

  <div class="info">
    <h3>关于 Svelte</h3>
    <p>Svelte 是一个全新的前端框架，它在构建时将代码转换为高效的原生 JavaScript，而不是在运行时解释。</p>
  </div>

  <div class="status">
    ✅ 运行中...
  </div>

  <p class="footer">由 DemoGo 支持</p>
</main>

<style>
  main {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 20px;
  }

  h1 {
    color: white;
    font-size: 2.5rem;
    margin-bottom: 10px;
    text-shadow: 0 2px 10px rgba(0,0,0,0.2);
  }

  .subtitle {
    color: rgba(255,255,255,0.9);
    font-size: 1.1rem;
    margin-bottom: 40px;
  }

  .counter {
    background: white;
    border-radius: 16px;
    padding: 40px;
    text-align: center;
    box-shadow: 0 20px 60px rgba(0,0,0,0.3);
  }

  .counter p {
    color: #333;
    font-size: 1.5rem;
    margin-bottom: 20px;
  }

  .counter button {
    background: #667eea;
    color: white;
    border: none;
    padding: 15px 40px;
    border-radius: 8px;
    font-size: 1.1rem;
    cursor: pointer;
    transition: transform 0.2s, background 0.2s;
  }

  .counter button:hover {
    background: #5a67d8;
    transform: scale(1.05);
  }

  .counter button:active {
    transform: scale(0.95);
  }

  .info {
    margin-top: 40px;
    background: rgba(255,255,255,0.95);
    border-radius: 12px;
    padding: 30px;
    max-width: 500px;
  }

  .info h3 {
    color: #667eea;
    margin-bottom: 15px;
  }

  .info p {
    color: #4a5568;
    line-height: 1.6;
  }

  .status {
    margin-top: 30px;
    padding: 15px 30px;
    background: #dcfce7;
    border: 1px solid #22c55e;
    border-radius: 8px;
    color: #166534;
  }

  .footer {
    margin-top: 30px;
    color: rgba(255,255,255,0.8);
    font-size: 0.85rem;
  }
</style>
